apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: hello-vm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: hello-vm
    spec:
      domain:
        devices:
          disks:
          - name: containerdisk
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
      volumes:
      - name: containerdisk
        containerDisk:
          image: quay.io/kubevirt/cirros-container-disk-demo
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #cloud-config
            password: password
            chpasswd: { expire: False }
